import { readFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";

const TITLE_PREFIX = "Feed audit:";

interface Verdict {
  name: string;
  url: string;
  verdict: string;
  finalUrl?: string;
  redirected?: boolean;
  itemCount?: number;
  newestAgeDays?: number | null;
  note?: string;
}

function isTransient(v: Verdict): boolean {
  if (["TIMEOUT", "HTTP_429", "HTTP_502", "HTTP_503"].includes(v.verdict)) return true;
  const host = (() => {
    try {
      return new URL(v.url).hostname;
    } catch {
      return "";
    }
  })();
  if (host.includes("substack.com") && ["HTTP_403", "HTTP_429", "TIMEOUT"].includes(v.verdict)) return true;
  return false;
}

function gh(args: string[], json = false): string {
  const out = execFileSync("gh", args, { encoding: "utf-8", stdio: ["ignore", "pipe", "pipe"] });
  return json ? out : out.trim();
}

function formatBody(actionable: Verdict[], transient: Verdict[], moved: Verdict[]): string {
  const lines: string[] = [
    `_Updated ${new Date().toISOString()}_`,
    "",
    "Generated by the weekly `feed-audit.yml` workflow. Transient Substack failures are listed separately.",
    "",
  ];

  if (actionable.length) {
    lines.push(`## Actionable (${actionable.length})`, "");
    for (const v of actionable) {
      const extra = [
        v.note,
        v.newestAgeDays != null ? `newest ${v.newestAgeDays}d` : null,
        v.itemCount != null ? `${v.itemCount} items` : null,
      ]
        .filter(Boolean)
        .join(", ");
      lines.push(`- **${v.verdict}** — ${v.name} — ${v.url}${extra ? ` (${extra})` : ""}`);
    }
    lines.push("");
  }

  if (moved.length) {
    lines.push(`## Permanently moved (${moved.length})`, "");
    lines.push("Update `scripts/sources.ts` to the final URL:", "");
    for (const v of moved) {
      lines.push(`- ${v.name}: \`${v.url}\` → \`${v.finalUrl}\``);
    }
    lines.push("");
  }

  if (transient.length) {
    lines.push(`## Transient / known-benign (${transient.length})`, "");
    for (const v of transient) {
      lines.push(`- **${v.verdict}** — ${v.name}`);
    }
    lines.push("");
  }

  lines.push("Fix: edit `scripts/sources.ts`, then `npm run validate:feeds`.");
  return lines.join("\n");
}

async function main() {
  const path = process.env.VALIDATE_OUT;
  if (!path) {
    console.log("report-feed-audit: VALIDATE_OUT not set — skipping");
    return;
  }

  let verdicts: Verdict[];
  try {
    verdicts = JSON.parse(await readFile(path, "utf-8")) as Verdict[];
  } catch (e) {
    console.warn("report-feed-audit: could not read verdicts:", e);
    return;
  }

  const bad = verdicts.filter((v) => v.verdict !== "OK");
  const actionable = bad.filter((v) => !isTransient(v));
  const transient = bad.filter(isTransient);
  const moved = verdicts.filter((v) => v.redirected && v.verdict === "OK");
  const problemCount = actionable.length + moved.length;

  let existing: { number: number; title: string } | null = null;
  try {
    const raw = gh(
      ["issue", "list", "--state", "open", "--search", `${TITLE_PREFIX} in:title`, "--json", "number,title", "--limit", "20"],
      true,
    );
    const issues = JSON.parse(raw) as { number: number; title: string }[];
    existing = issues.find((i) => i.title.startsWith(TITLE_PREFIX)) ?? null;
  } catch (e) {
    console.warn("report-feed-audit: gh issue list failed (ok when not in CI):", e instanceof Error ? e.message : e);
    return;
  }

  if (problemCount === 0) {
    if (existing) {
      gh(["issue", "close", String(existing.number), "--comment", "Latest weekly audit is clean. Closing."]);
      console.log(`Closed issue #${existing.number} — audit clean`);
    } else {
      console.log("Audit clean — no issue to open");
    }
    return;
  }

  const title = `${TITLE_PREFIX} ${problemCount} problem${problemCount === 1 ? "" : "s"}`;
  const body = formatBody(actionable, transient, moved);

  if (existing) {
    gh(["issue", "edit", String(existing.number), "--title", title, "--body", body]);
    console.log(`Updated issue #${existing.number}: ${title}`);
  } else {
    gh(["issue", "create", "--title", title, "--body", body]);
    console.log(`Opened issue: ${title}`);
  }
}

main().catch((e) => {
  console.error("report-feed-audit failed:", e);
  process.exit(1);
});
